- config.json
- src/server/services/user/user.service.ts
Save identifier.
Default mockLicenses to false
> fix(user): actually save license for player, set mockLicenses to false

- package.json
> fix: remove use of -r in script

- src/server/utils/dbUtils.ts
- src/server/utils/pool.ts
> fix: stole npwd DB parser

- config.json
- package.json
- src/client/client.ts
- src/server/globals.server.ts
- src/server/server.ts
- src/server/services/account/account.controller.ts
- src/server/services/account/account.service.ts
- src/server/services/accountExternal/externalAccount.service.ts
- src/server/services/boot/boot.service.ts
- src/server/services/cash/cash.controller.ts
- src/server/services/cash/cash.service.ts
- src/server/services/invoice/invoice.controller.ts
- src/server/services/user/user.controller.ts
- src/server/services/user/user.module.ts
- src/server/services/user/user.service.ts
- src/server/utils/constants.ts
- src/server/utils/frameworkIntegration.ts
- src/server/utils/misc.ts
- typings/Events.ts
- typings/config.ts
- typings/exports.ts
- typings/exports/server.ts
- web/src/utils/constants.ts
> fix(framework-integration): redesigned implementation

- src/server/utils/misc.ts
- web/src/components/Modals/CreateAccount.tsx
- web/src/components/ui/Checkbox.tsx
> fix: getExports when isMocking, create account

- src/server/globals.server.ts
- src/server/server.ts
- src/server/services/account/account.controller.ts
- src/server/services/account/account.service.ts
- src/server/services/boot/boot.service.ts
- src/server/services/user/user.controller.ts
- src/server/services/user/user.service.ts
- src/server/utils/frameworkIntegration.ts
- src/server/utils/misc.ts
- typings/Events.ts
- typings/exports.ts
- typings/exports/server.ts
Added export to be used with framework integration to load players programatically
> Framework integration load player

- src/server/services/account/account.controller.ts
- src/server/services/user/user.service.ts
> fix: send correct data for playerLoaded

- config.json
- typings/config.ts
- web/src/components/Layout.tsx
- web/src/utils/constants.ts
- web/src/views/dashboard/components/AccountCards.tsx
- web/src/views/dashboard/components/__tests__/AccountCards.test.tsx
Display more accounts without breaking, adjustable in conf
> feat: maximumNumberOfAccounts

- src/server/services/account/account.service.ts
Couldn't add to unique accounts, a typo.
> fix(services/account): fixed adding to unique accounts

- src/server/services/account/account.service.ts
- typings/Errors.ts
- Don't add to the sharedaccount if the user already is in it.
- Actually remove the user from the shared account when removing.
> fix(services/account): removeFromUniqueAccount

- .github/workflows/release.yml
> ignore scripts in ci

- .github/workflows/release.yml
> ci(release): generate locales

- typings/config.ts
- web/src/components/Modals/AddUser.tsx
- web/src/components/Modals/RemoveUser.tsx
- web/src/components/TransferFunds.tsx
- web/src/mobileDevelopmentContainer.tsx
- web/src/views/accounts/SharedSettings.tsx
> fix: tsfixes & uniqueaccount fixes

- fxmanifest.lua
- scripts/release.sh
- src/client/lua/interaction.lua
> feat(client): add interaction helper text if target is disabled

- src/client/lua/interaction.lua
I've updated it to make it work without restarting the resource, not sure if it's the good way to do it but it's working.
> Fix markers

- web/src/components/Card.tsx
> feat: added discrete copy number button on card

- src/server/services/account/account.controller.ts
- src/server/services/account/account.service.ts
- typings/Account.ts
- typings/exports/server.ts
exports functions to manipulate account by account number
```lua
exports.pefcl:addBankBalanceByNumber(source, { accountNumber, amount, message })
exports.pefcl:removeBankBalanceByNumber(source, { accountNumber, amount, message })
```
> feat(exports): add/remove money by account number

- package.json
- src/client/cl_integrations.ts
- src/client/i18n.ts
> fix: client side translations

- src/server/services/accountShared/sharedAccount.db.ts
- src/server/services/transaction/transaction.service.ts
> fix: give owner full access

- src/server/services/boot/boot.service.ts
> fix: better error message for framework integration

- .github/workflows/prerelease.yml
- package.json
- scripts/prerelease.sh
- scripts/release.sh
> fix: remove prerelease hook

- src/client/cl_exports.ts
- src/server/services/cash/cash.service.ts
**Fixed giveCash and matched export types to documentation**
_The giveCash function in the CashService used an unknown variable which would
trigger the UserNotFound error._
_The types on the client exports did not match the documentation._
> Fixed giveCash and matched export types to documentation

- typings/Invoice.ts
> fix: receiverAccountIdentifier

- web/src/App.tsx
This reverts commit b726f5108fb3110f3b8a01cbd512e76f4a3ad067.
> Revert "fix(accounts): ui refresh on loadPlayer (#74)"

- src/server/services/account/account.service.ts
> fix: use correct event for changeDefaultAccount

- src/server/services/account/account.model.ts
> fix(accounts): removed alphanumeric validation

- web/src/views/Deposit/Deposit.tsx
- web/src/views/Withdraw/Withdraw.tsx
> fix: update balance on withdraw & deposit

- web/tsconfig.json
- web/webpack.config.js
> fix: perhaps smoler bundle

- src/server/services/account/account.service.ts
> fix: debug instead of error for adding unique account user

- src/server/services/account/account.db.ts
- src/server/services/invoice/invoice.db.ts
- src/server/services/invoice/invoice.service.ts
No paying paid invoices any longer
> fix(invoices): throw error when trying to pay paid invoice

- web/npwd.config.ts
Adds an notification icon property for NPWD notifications
> feat(web/npwd-config): add notification icon

- src/server/services/account/account.controller.ts
- src/server/services/account/account.service.ts
- src/server/services/cash/cash.controller.ts
- src/server/services/invoice/invoice.db.ts
Display of invoices from most recent to oldest to simplify navigation in PEFCL
> fix: order invoices by createdAt DESC

- src/server/services/account/account.service.ts
- web/src/views/Mobile/Mobile.tsx
- web/src/views/Mobile/Routes.tsx
The router was broken, the router is now fixed.
Plus i added a check for whether a user existed before trying to emit and event, this was because if the function was triggered on a player disconnecting it would try and emit the event producing a script execution host error
> Fixes for NPWD 1.7.1+

- src/client/cl_events.ts
- src/client/client.ts
- src/package.json
- src/yarn.lock
- web/index.html
- web/npwd.config.ts
- web/package.json
- web/src/App.tsx
- web/src/hooks/useBroadcasts.ts
- web/src/hooks/useNuiEvent.ts
- web/src/views/ATM/ATM.tsx
- web/src/views/Mobile/Mobile.tsx
- web/vite.config.ts
- web/yarn.lock
> feat(web): initial update to vite
